### ISSUE TITLE
Co-host rqt_launchtree on rqt_launch repository?

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_launch#17]
@pschillinger `rqt_launch` is now hosted here as a single-package-repo. Since your [rqt_launchtree](https://github.com/pschillinger/rqt_launchtree) provides similar but unique feature, would you want to move that package here? Benefit for you is you'll get co-maintainers (currently me and @rsinnet). And community will likely benefit from better visibility since it's `ros-*` organization and `launch` related packages kept at one place. You'll remain as the author of `rqt_launchtree` of course.

I suggest the package structure will become something like:

```
rqt_launch repository
|- rqt_launch
|- rqt_launchtree
|- rqt_launch_meta
```

`rqt_launch_meta` is just a [metapackage](http://wiki.ros.org/Metapackages).

**Comment by dirk-thomas** [comment]
Just a comment: you can always move your repository to this org unit and we will give you full admin access to the repo. It doesn't necessarily have to be merged into this repo but could be a sibling.

**Comment by 130s** [comment]
Ok, I take this back. As I left a comment in the [ML](https://groups.google.com/d/msg/ros-sig-rqt/CMGkwUndJMI/wTdq6jarBQAJ), consolidating repos might be the most beneficial as certain situation when there's a dependency between packages that are hosted at separate repos. Since `rqt_launchtree` and `rqt_launch` don't depend on each other, there's no such an advantage.

@pschillinger You can still request to move your repo to ros-visualization as @dirk-thomas said.
